apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Edelivery.Mobile.Login
  description: Bff para implementacoes para fluxos de autenticacao 
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: artistweb
  tags:
    - .net core 6.0
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: public-websites
  definition:
    $text: https://api-stage-edelivery.febrafar.com.br/mobile/login/swagger/v1/swagger.json
