apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web-site
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  providesApis:
    - auth-api
